package com.simba.themestore.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.simba.themestore.model.personal.PersonalThemeBean;
import com.simba.themestore.model.personal.PersonalWallPaperBean;

import com.simba.themestore.database.PersonalThemeBeanDao;
import com.simba.themestore.database.PersonalWallPaperBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personalThemeBeanDaoConfig;
    private final DaoConfig personalWallPaperBeanDaoConfig;

    private final PersonalThemeBeanDao personalThemeBeanDao;
    private final PersonalWallPaperBeanDao personalWallPaperBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personalThemeBeanDaoConfig = daoConfigMap.get(PersonalThemeBeanDao.class).clone();
        personalThemeBeanDaoConfig.initIdentityScope(type);

        personalWallPaperBeanDaoConfig = daoConfigMap.get(PersonalWallPaperBeanDao.class).clone();
        personalWallPaperBeanDaoConfig.initIdentityScope(type);

        personalThemeBeanDao = new PersonalThemeBeanDao(personalThemeBeanDaoConfig, this);
        personalWallPaperBeanDao = new PersonalWallPaperBeanDao(personalWallPaperBeanDaoConfig, this);

        registerDao(PersonalThemeBean.class, personalThemeBeanDao);
        registerDao(PersonalWallPaperBean.class, personalWallPaperBeanDao);
    }
    
    public void clear() {
        personalThemeBeanDaoConfig.clearIdentityScope();
        personalWallPaperBeanDaoConfig.clearIdentityScope();
    }

    public PersonalThemeBeanDao getPersonalThemeBeanDao() {
        return personalThemeBeanDao;
    }

    public PersonalWallPaperBeanDao getPersonalWallPaperBeanDao() {
        return personalWallPaperBeanDao;
    }

}
